"""Analytics API - Usage statistics and ROI tracking."""
from datetime import datetime, timedelta
from fastapi import APIRouter, Depends
from app.database import get_db
from app.api.auth import get_current_user_id

router = APIRouter()

# Time estimates (in minutes) for manual content creation
TIME_ESTIMATES = {
    "linkedin": 30,  # 30 min per LinkedIn post manually
    "blog": 120,     # 2 hours per blog post manually
    "email": 20,     # 20 min per email manually
    "email_sequence": 150,  # 2.5 hours for 5-email sequence
}

# Cost estimates for outsourcing (in dollars)
OUTSOURCE_COSTS = {
    "linkedin": 50,
    "blog": 200,
    "email": 35,
    "email_sequence": 250,
}


@router.get("/analytics")
async def get_analytics(
    days: int = 30,
    user_id: int = Depends(get_current_user_id),
):
    """
    Get comprehensive usage analytics for the current user.

    Returns:
    - Total content generated by type
    - Total cost incurred
    - Estimated time saved
    - Estimated cost savings vs outsourcing
    - Daily activity breakdown
    - Quality score averages
    """
    cutoff_date = datetime.now() - timedelta(days=days)

    async with get_db() as db:
        # Total jobs and cost
        cursor = await db.execute(
            """
            SELECT
                COUNT(*) as total_jobs,
                COALESCE(SUM(cost_incurred), 0) as total_cost,
                MIN(created_at) as first_job,
                MAX(created_at) as last_job
            FROM jobs
            WHERE user_id = ? AND created_at >= ?
            """,
            (user_id, cutoff_date.isoformat())
        )
        job_stats = await cursor.fetchone()

        # Content by type
        cursor = await db.execute(
            """
            SELECT
                o.content_type,
                COUNT(*) as count,
                AVG(json_extract(o.quality_scores, '$.overall_score')) as avg_quality
            FROM outputs o
            JOIN jobs j ON o.job_id = j.id
            WHERE j.user_id = ? AND j.created_at >= ?
            GROUP BY o.content_type
            ORDER BY count DESC
            """,
            (user_id, cutoff_date.isoformat())
        )
        content_by_type = {}
        total_time_saved = 0
        total_outsource_savings = 0

        for row in await cursor.fetchall():
            content_type = row["content_type"]
            count = row["count"]

            # Calculate time saved
            time_per = TIME_ESTIMATES.get(content_type, 30)
            time_saved = count * time_per

            # Calculate outsource cost savings
            outsource_per = OUTSOURCE_COSTS.get(content_type, 50)
            outsource_savings = count * outsource_per

            content_by_type[content_type] = {
                "count": count,
                "avg_quality": round(row["avg_quality"], 1) if row["avg_quality"] else None,
                "time_saved_minutes": time_saved,
                "outsource_equivalent": outsource_savings,
            }

            total_time_saved += time_saved
            total_outsource_savings += outsource_savings

        # Daily activity (last 30 days)
        cursor = await db.execute(
            """
            SELECT
                DATE(created_at) as date,
                COUNT(*) as jobs,
                COALESCE(SUM(cost_incurred), 0) as cost
            FROM jobs
            WHERE user_id = ? AND created_at >= ?
            GROUP BY DATE(created_at)
            ORDER BY date DESC
            LIMIT 30
            """,
            (user_id, cutoff_date.isoformat())
        )
        daily_activity = []
        for row in await cursor.fetchall():
            daily_activity.append({
                "date": row["date"],
                "jobs": row["jobs"],
                "cost": round(row["cost"], 4),
            })

        # Feedback summary
        cursor = await db.execute(
            """
            SELECT
                f.feedback_type,
                COUNT(*) as count
            FROM output_feedback f
            JOIN outputs o ON f.output_id = o.id
            JOIN jobs j ON o.job_id = j.id
            WHERE f.user_id = ?
            GROUP BY f.feedback_type
            """,
            (user_id,)
        )
        feedback = {"up": 0, "down": 0}
        for row in await cursor.fetchall():
            feedback[row["feedback_type"]] = row["count"]

        # Atoms extracted
        cursor = await db.execute(
            """
            SELECT COUNT(*) as count
            FROM atoms
            WHERE user_id = ? AND created_at >= ?
            """,
            (user_id, cutoff_date.isoformat())
        )
        atom_row = await cursor.fetchone()
        atoms_extracted = atom_row["count"] if atom_row else 0

        # Calculate totals
        total_outputs = sum(c["count"] for c in content_by_type.values())
        total_cost = job_stats["total_cost"] if job_stats else 0

        # Calculate ROI
        roi_percentage = 0
        if total_cost > 0 and total_outsource_savings > 0:
            roi_percentage = round(((total_outsource_savings - total_cost) / total_cost) * 100, 1)

        # Cost per piece
        cost_per_piece = round(total_cost / total_outputs, 4) if total_outputs > 0 else 0

        return {
            "period_days": days,
            "summary": {
                "total_jobs": job_stats["total_jobs"] if job_stats else 0,
                "total_outputs": total_outputs,
                "total_cost": round(total_cost, 4),
                "cost_per_piece": cost_per_piece,
                "atoms_extracted": atoms_extracted,
            },
            "time_savings": {
                "minutes_saved": total_time_saved,
                "hours_saved": round(total_time_saved / 60, 1),
                "days_saved": round(total_time_saved / 60 / 8, 1),  # 8-hour work days
            },
            "cost_savings": {
                "outsource_equivalent": total_outsource_savings,
                "actual_cost": round(total_cost, 2),
                "savings": round(total_outsource_savings - total_cost, 2),
                "roi_percentage": roi_percentage,
            },
            "content_by_type": content_by_type,
            "daily_activity": daily_activity,
            "feedback": feedback,
            "quality": {
                "avg_score": round(
                    sum(c["avg_quality"] for c in content_by_type.values() if c["avg_quality"]) /
                    len([c for c in content_by_type.values() if c["avg_quality"]])
                    if any(c["avg_quality"] for c in content_by_type.values()) else 0, 1
                ),
                "thumbs_up_rate": round(
                    feedback["up"] / (feedback["up"] + feedback["down"]) * 100
                    if (feedback["up"] + feedback["down"]) > 0 else 0, 1
                ),
            },
        }


@router.get("/analytics/lifetime")
async def get_lifetime_analytics(
    user_id: int = Depends(get_current_user_id),
):
    """Get all-time analytics for the user."""
    return await get_analytics(days=3650, user_id=user_id)  # 10 years
